# Generated by Django 3.0.7 on 2020-12-09 18:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('primary_email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='primary_email')),
                ('primary_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('primary_fax', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('primary_address', models.CharField(blank=True, max_length=200, null=True)),
                ('primary_address2', models.CharField(blank=True, max_length=200, null=True)),
                ('primary_city', models.CharField(blank=True, max_length=200, null=True)),
                ('primary_state', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_zip_code', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,5}$')])),
                ('primary_country', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_email', models.EmailField(blank=True, max_length=60, null=True, unique=True, verbose_name='billing_email')),
                ('billing_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('billing_fax', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('billing_address', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_address2', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_zip_code', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,5}$')])),
                ('billing_country', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_email', models.EmailField(blank=True, max_length=60, null=True, unique=True, verbose_name='shipping_email')),
                ('shipping_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('shipping_fax', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('shipping_address', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_address2', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_state', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_zip_code', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,5}$')])),
                ('shipping_country', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('global_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='merchant/profile/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='merchant/logo/')),
            ],
            options={
                'ordering': ['name', 'date_added'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('body', models.FileField(blank=True, null=True, upload_to='merchant/email/templates/')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.Merchant')),
            ],
            options={
                'ordering': ['title', 'date_added'],
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('ssl', models.BooleanField(default=False)),
                ('tls', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.Merchant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
