# Generated by Django 2.1.12 on 2020-06-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbarcode',
            name='barcode_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbarcode',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
