# Generated by Django 3.0.7 on 2020-07-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200627_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='street_address',
            new_name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
