# Generated by Django 3.0.7 on 2020-08-21 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200721_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='barcode',
        ),
        migrations.DeleteModel(
            name='UserBarcode',
        ),
    ]
