# Generated by Django 3.0.7 on 2020-08-21 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200821_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,4}$')]),
        ),
    ]
